Repository Team-Shaka/Treehouse-SpringBoot, pull requests merged in 2024-04, with the labels that each got.

#3 ✨ Feat: github issue, PR Template 생성
  .github/ISSUE_TEMPLATE/🐛-bug-.md
  .github/ISSUE_TEMPLATE/👷️-ci-.md
  .github/ISSUE_TEMPLATE/📝-docs-.md
  .github/ISSUE_TEMPLATE/🔨-refactor-.md
  .github/ISSUE_TEMPLATE/🚀--feature-.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :sparkles: feat

#7 [CI] 👷 ci/cd 파이프라인 구축
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  src/main/java/treehouse/server/api/root/presentation/RootApi.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :sparkles: feat, :construction_worker: ci

#9 [CI,BUG] 🐛 Fix : docker 설정 추가
  Dockerfile
  Dockerrun.aws.json
  dev_start.sh
Labels: :bug: bug, :construction_worker: ci

#10 [CI, Bug] 🐛 Fix : ci/cd 파이프라인 ebextensions 추가
  .ebextensions/00-set-timezone.config
Labels: :bug: bug, :construction_worker: ci

#11 ✨ Feat : API 응답통일, 에러핸들러 설계
  build.gradle
  src/main/java/treehouse/server/global/common/CommonResponse.java
  src/main/java/treehouse/server/global/exception/BaseErrorCode.java
  src/main/java/treehouse/server/global/exception/GeneralExceptionHandler.java
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
  src/main/java/treehouse/server/global/exception/ThrowClass/GeneralException.java
  src/main/java/treehouse/server/global/exception/dto/ErrorResponseDTO.java
Labels: :sparkles: feat

#15 🐛 Bug: test 삭제
  src/test/java/treehouse/server/ServerApplicationTests.java
Labels: :bug: bug

#16 ✨ Feat : spring security 추가
  build.gradle
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
  src/main/java/treehouse/server/global/exception/JwtAuthenticationException.java
  src/main/java/treehouse/server/global/security/config/SecurityConfig.java
  src/main/java/treehouse/server/global/security/filter/JwtAuthFilter.java
  src/main/java/treehouse/server/global/security/handler/JwtAccessDeniedHandler.java
  src/main/java/treehouse/server/global/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/treehouse/server/global/security/handler/JwtAuthenticationExceptionHandler.java
  src/main/java/treehouse/server/global/security/handler/annotation/AuthMember.java
  src/main/java/treehouse/server/global/security/provider/TokenProvider.java
Labels: :sparkles: feat

#18 ✨ Feat : 로그인, 회원가입, 토큰 재발급 API
  build.gradle
  src/main/java/treehouse/server/ServerApplication.java
  src/main/java/treehouse/server/api/ncp/business/NcpService.java
  src/main/java/treehouse/server/api/user/business/UserMapper.java
  src/main/java/treehouse/server/api/user/business/UserService.java
  src/main/java/treehouse/server/api/user/implement/UserCommandAdapter.java
  src/main/java/treehouse/server/api/user/implement/UserQueryAdapter.java
  src/main/java/treehouse/server/api/user/persistence/UserRepository.java
  src/main/java/treehouse/server/api/user/presentation/UserApi.java
  src/main/java/treehouse/server/api/user/presentation/dto/UserRequestDTO.java
  src/main/java/treehouse/server/api/user/presentation/dto/UserResponseDTO.java
  src/main/java/treehouse/server/global/annotations/Adapter.java
  src/main/java/treehouse/server/global/config/SwaggerConfig.java
  src/main/java/treehouse/server/global/constants/UserRole.java
  src/main/java/treehouse/server/global/entity/redis/RefreshToken.java
  src/main/java/treehouse/server/global/exception/ThrowClass/AuthException.java
  src/main/java/treehouse/server/global/exception/ThrowClass/UserException.java
  src/main/java/treehouse/server/global/redis/repository/RefreshTokenRepository.java
  src/main/java/treehouse/server/global/redis/service/RedisService.java
  src/main/java/treehouse/server/global/security/jwt/dto/TokenDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feat
