Repository Team-Shaka/Treehouse-SpringBoot, pull requests merged in 2024-09, with the labels that each got.

#117 ⚡️ Refactor: 브랜치 뷰 url 변경 및 트리하우스 가입 시, 브랜치 자동 생성
  src/main/java/treehouse/server/api/branch/business/BranchService.java
  src/main/java/treehouse/server/api/branch/presentation/BranchApi.java
  src/main/java/treehouse/server/api/invitation/business/InvitationService.java
  src/main/java/treehouse/server/api/invitation/implement/InvitationQueryAdapter.java
  src/main/java/treehouse/server/api/invitation/persistence/InvitationRepository.java
  src/main/java/treehouse/server/api/member/business/MemberService.java
  src/main/java/treehouse/server/global/security/config/SecurityConfig.java
Labels: :recycle: refactor, :hammer: code_edit

#119 ✨ Feat: 트리하우스 창립자 가입 API
  src/main/java/treehouse/server/api/member/business/MemberService.java
  src/main/java/treehouse/server/api/member/presentation/MemberApi.java
Labels: :sparkles: feat

#121 ✨ Feat: 한 유저당 하나의 FCM Token 값을 저장하도록 수정
  src/main/java/treehouse/server/api/user/persistence/FcmTokenRepository.java
  src/main/java/treehouse/server/global/entity/User/FcmToken.java
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
  src/main/java/treehouse/server/global/fcm/service/FcmService.java
Labels: :sparkles: feat

#123 🐛 Fix: 알림 생성이 필요한 로직들에서 userId를 지정하도록 수정
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/post/business/PostService.java
Labels: :bug: bug, :hammer: code_edit

#124 🐛 푸시알림 senderName 출력되지 않는 문제 해결
  src/main/java/treehouse/server/api/notification/business/NotificationService.java
Labels: :bug: bug

#126 ⚡️ Fix: 회원가입 시 초대장 처리 및 트리하우스 가입 유효성 검사
  src/main/java/treehouse/server/api/invitation/implement/InvitationQueryAdapter.java
  src/main/java/treehouse/server/api/invitation/persistence/InvitationRepository.java
  src/main/java/treehouse/server/api/member/presentation/MemberApi.java
  src/main/java/treehouse/server/api/member/presentation/dto/MemberRequestDTO.java
  src/main/java/treehouse/server/api/user/business/UserService.java
  src/main/java/treehouse/server/global/entity/Invitation/Invitation.java
  src/main/java/treehouse/server/global/entity/member/Member.java
Labels: :bug: bug, :hammer: code_edit

#128 ♻️ Refactor: 프로필 조회 시, 전화번호 추가
  src/main/java/treehouse/server/api/member/business/MemberMapper.java
  src/main/java/treehouse/server/api/member/presentation/dto/MemberResponseDTO.java
Labels: :recycle: refactor, :hammer: code_edit

#131 ⚡️ Improve: 초대장 로직 개선
  src/main/java/treehouse/server/api/invitation/business/InvitationService.java
  src/main/java/treehouse/server/api/invitation/implement/InvitationCommandAdapter.java
  src/main/java/treehouse/server/api/invitation/implement/InvitationQueryAdapter.java
  src/main/java/treehouse/server/api/member/business/MemberService.java
  src/main/resources/application.yml
Labels: :hammer: code_edit

#132 📝 Refactor: 댓글 출력 순서 변경(가장 최근 작성한 것이 가장 마지막으로)
  src/main/java/treehouse/server/api/comment/business/CommentService.java
Labels: :hammer: code_edit

#134 ✨ Feat: 리프레시 토큰 시간 1시간으로 변경
  src/main/resources/application.yml
Labels: :hammer: code_edit

#135 ⚡️ Improve: 유저 회원가입 시 유효성 검사
  build.gradle
  src/main/java/treehouse/server/api/user/presentation/dto/UserRequestDTO.java
  src/main/java/treehouse/server/global/entity/User/User.java
Labels: :hammer: code_edit

#137 ♻️ Refactor: 토큰 유효시간 증가와 활동량 로직 추가
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/post/business/PostService.java
  src/main/java/treehouse/server/global/entity/User/User.java
  src/main/resources/application.yml
Labels: :recycle: refactor, :hammer: code_edit
