Repository Team-Shaka/Treehouse-SpringBoot, pull requests merged in 2024-06, with the labels that each got.

#45 Feat: 전화번호를 이용한 유저 상태 확인 API 구현
  src/main/java/treehouse/server/api/invitation/implement/InvitationQueryAdapter.java
  src/main/java/treehouse/server/api/invitation/persistence/InvitationRepository.java
  src/main/java/treehouse/server/api/user/business/UserMapper.java
  src/main/java/treehouse/server/api/user/business/UserService.java
  src/main/java/treehouse/server/api/user/implement/UserQueryAdapter.java
  src/main/java/treehouse/server/api/user/presentation/UserApi.java
  src/main/java/treehouse/server/api/user/presentation/dto/UserRequestDTO.java
  src/main/java/treehouse/server/api/user/presentation/dto/UserResponseDTO.java
Labels: :sparkles: feat

#46 ✨ Feat : 게시글 신고 API 구현
  src/main/java/treehouse/server/api/post/business/PostMapper.java
  src/main/java/treehouse/server/api/post/business/PostService.java
  src/main/java/treehouse/server/api/post/presentation/PostApi.java
  src/main/java/treehouse/server/api/post/presentation/dto/PostRequestDTO.java
  src/main/java/treehouse/server/api/report/implementation/ReportCommandAdapter.java
  src/main/java/treehouse/server/api/report/persistent/ReportRepository.java
  src/main/java/treehouse/server/global/entity/report/Report.java
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
Labels: :sparkles: feat

#48 ✨ Feat : 댓글 신고 API 구현
  src/main/java/treehouse/server/api/comment/business/CommentMapper.java
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/comment/implementation/CommentCommandAdapter.java
  src/main/java/treehouse/server/api/comment/implementation/CommentQueryAdapter.java
  src/main/java/treehouse/server/api/comment/persistence/CommentRepository.java
  src/main/java/treehouse/server/api/comment/presentation/CommentApi.java
  src/main/java/treehouse/server/api/comment/presentation/dto/CommentRequestDTO.java
  src/main/java/treehouse/server/api/comment/presentation/dto/CommentResponseDTO.java
  src/main/java/treehouse/server/api/post/business/PostMapper.java
  src/main/java/treehouse/server/api/post/business/PostService.java
  src/main/java/treehouse/server/api/report/business/ReportMapper.java
  src/main/java/treehouse/server/global/entity/comment/Comment.java
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
  src/main/java/treehouse/server/global/exception/ThrowClass/CommentException.java
Labels: :sparkles: feat

#49 ✨ Feat : 댓글 작성, 목록 조회, 삭제 API 구현
  src/main/java/treehouse/server/api/comment/business/CommentMapper.java
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/comment/implementation/CommentCommandAdapter.java
  src/main/java/treehouse/server/api/comment/implementation/CommentQueryAdapter.java
  src/main/java/treehouse/server/api/comment/persistence/CommentRepository.java
  src/main/java/treehouse/server/api/comment/presentation/CommentApi.java
  src/main/java/treehouse/server/api/comment/presentation/dto/CommentRequestDTO.java
  src/main/java/treehouse/server/api/comment/presentation/dto/CommentResponseDTO.java
  src/main/java/treehouse/server/api/member/implementation/MemberQueryAdapter.java
  src/main/java/treehouse/server/api/post/business/PostService.java
  src/main/java/treehouse/server/api/reaction/presentation/dto/ReactionRequestDTO.java
  src/main/java/treehouse/server/api/reaction/presentation/dto/ReactionResponseDTO.java
  src/main/java/treehouse/server/api/report/implementation/ReportQueryAdapter.java
  src/main/java/treehouse/server/api/report/persistent/ReportRepository.java
  src/main/java/treehouse/server/global/entity/comment/Comment.java
Labels: :sparkles: feat

#51 Refactor: 기존 유저 로그인 API 수정
  src/main/java/treehouse/server/api/member/business/MemberMapper.java
  src/main/java/treehouse/server/api/member/business/MemberService.java
  src/main/java/treehouse/server/api/user/business/UserMapper.java
  src/main/java/treehouse/server/api/user/business/UserService.java
  src/main/java/treehouse/server/api/user/implement/UserQueryAdapter.java
  src/main/java/treehouse/server/api/user/presentation/UserApi.java
  src/main/java/treehouse/server/api/user/presentation/dto/UserResponseDTO.java
Labels: :recycle: refactor

#59 🐛 Fix: 토큰 유효기간 변경
  src/main/resources/application.yml
Labels: :hammer: code_edit

#56 Feature/52 게시글/댓글에 감정표현을 남기는 API 구현
  src/main/java/treehouse/server/api/comment/business/CommentMapper.java
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/comment/presentation/CommentApi.java
  src/main/java/treehouse/server/api/comment/presentation/dto/CommentRequestDTO.java
  src/main/java/treehouse/server/api/comment/presentation/dto/CommentResponseDTO.java
  src/main/java/treehouse/server/api/post/business/PostMapper.java
  src/main/java/treehouse/server/api/post/business/PostService.java
  src/main/java/treehouse/server/api/post/implement/PostQueryAdapter.java
  src/main/java/treehouse/server/api/post/persistence/PostRepository.java
  src/main/java/treehouse/server/api/post/presentation/PostApi.java
  src/main/java/treehouse/server/api/post/presentation/dto/PostRequestDTO.java
  src/main/java/treehouse/server/api/post/presentation/dto/PostResponseDTO.java
  src/main/java/treehouse/server/api/reaction/business/ReactionMapper.java
  src/main/java/treehouse/server/api/reaction/implementation/ReactionCommandAdapter.java
  src/main/java/treehouse/server/api/reaction/implementation/ReactionQueryAdapter.java
  src/main/java/treehouse/server/api/reaction/persistence/ReactionRepository.java
  src/main/java/treehouse/server/api/reaction/presentation/dto/ReactionRequestDTO.java
  src/main/java/treehouse/server/api/reaction/presentation/dto/ReactionResponseDTO.java
  src/main/java/treehouse/server/api/report/implementation/ReportQueryAdapter.java
  src/main/java/treehouse/server/api/report/persistent/ReportRepository.java
  src/main/java/treehouse/server/global/entity/reaction/Reaction.java
  src/main/java/treehouse/server/global/entity/reaction/ReactionType.java
Labels: :sparkles: feat

#62 ♻️ Refactor: Mapper 클래스 구조 변경과 NotificationType enum 추가
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/member/business/MemberMapper.java
  src/main/java/treehouse/server/api/member/business/MemberService.java
  src/main/java/treehouse/server/api/post/business/PostService.java
  src/main/java/treehouse/server/global/entity/User/User.java
  src/main/java/treehouse/server/global/entity/member/Member.java
  src/main/java/treehouse/server/global/entity/notification/NotificationType.java
  src/main/java/treehouse/server/global/entity/treeHouse/TreeHouse.java
Labels: :recycle: refactor

#65 ✨ Feat : 초대하기 API 구현
  src/main/java/treehouse/server/api/invitation/business/InvitationMapper.java
  src/main/java/treehouse/server/api/invitation/business/InvitationService.java
  src/main/java/treehouse/server/api/invitation/implement/InvitationCommandAdapter.java
  src/main/java/treehouse/server/api/invitation/presentation/InvitationApi.java
  src/main/java/treehouse/server/api/invitation/presentation/dto/InvitationRequestDTO.java
  src/main/java/treehouse/server/api/invitation/presentation/dto/InvitationResponseDTO.java
  src/main/java/treehouse/server/api/member/persistence/MemberRepository.java
Labels: :sparkles: feat

#66 🐛 Bug: InvitationMapper static 설정
  src/main/java/treehouse/server/api/invitation/business/InvitationMapper.java
  src/main/java/treehouse/server/api/invitation/business/InvitationService.java
Labels: :bug: bug

#68 브랜치 관련 레거시 코드
  src/main/java/treehouse/server/api/branch/business/BranchMapper.java
  src/main/java/treehouse/server/api/branch/business/BranchService.java
  src/main/java/treehouse/server/api/branch/implementation/BranchCommandAdapter.java
  src/main/java/treehouse/server/api/branch/implementation/BranchQueryAdapter.java
  src/main/java/treehouse/server/api/branch/persistence/BranchRepository.java
  src/main/java/treehouse/server/api/branch/presentation/BranchApi.java
  src/main/java/treehouse/server/api/branch/presentation/dto/BranchResponseDTO.java
  src/main/java/treehouse/server/api/member/implementation/MemberQueryAdapter.java
  src/main/java/treehouse/server/global/entity/branch/Branch.java
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
Labels: :sparkles: feat

#70 브랜치 관련 레거시 코드
  src/main/java/treehouse/server/api/branch/business/BranchMapper.java
  src/main/java/treehouse/server/api/branch/business/BranchService.java
  src/main/java/treehouse/server/api/branch/implementation/BranchCommandAdapter.java
  src/main/java/treehouse/server/api/branch/implementation/BranchQueryAdapter.java
  src/main/java/treehouse/server/api/branch/persistence/BranchRepository.java
  src/main/java/treehouse/server/api/branch/presentation/BranchApi.java
  src/main/java/treehouse/server/api/branch/presentation/dto/BranchResponseDTO.java
  src/main/java/treehouse/server/api/member/implementation/MemberQueryAdapter.java
  src/main/java/treehouse/server/global/entity/branch/Branch.java
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
Labels: :sparkles: feat
