Repository Team-Shaka/Treehouse-SpringBoot, pull requests merged in 2024-08, with the labels that each got.

#89 📝 DOCS: 트리하우스 생성 - 이름 관련 유효성 검사
  src/main/java/treehouse/server/api/treehouse/presentation/TreehouseApi.java
  src/main/java/treehouse/server/api/treehouse/presentation/dto/TreehouseRequestDTO.java
Labels: :hammer: code_edit

#91 ♻️ Refactor: 트리하우스 회원가입 API 수정
  src/main/java/treehouse/server/api/member/business/MemberMapper.java
  src/main/java/treehouse/server/api/member/presentation/dto/MemberResponseDTO.java
Labels: :recycle: refactor

#94 Refactor/92
  src/main/java/treehouse/server/api/notification/business/NotificationService.java
  src/main/java/treehouse/server/api/notification/business/NotificationUtil.java
  src/main/resources/application.yml
Labels: :hammer: code_edit

#95 📝 Dockerfile에 시간대 설정 추가
  Dockerfile
Labels: :memo: docs

#98 ✨ Feat: 트리하우스 이름 중복확인 API
  src/main/java/treehouse/server/api/treehouse/business/TreehouseMapper.java
  src/main/java/treehouse/server/api/treehouse/business/TreehouseService.java
  src/main/java/treehouse/server/api/treehouse/implementation/TreehouseQueryAdapter.java
  src/main/java/treehouse/server/api/treehouse/persistence/TreehouseRepository.java
  src/main/java/treehouse/server/api/treehouse/presentation/TreehouseApi.java
  src/main/java/treehouse/server/api/treehouse/presentation/dto/TreehouseRequestDTO.java
  src/main/java/treehouse/server/api/treehouse/presentation/dto/TreehouseResponseDTO.java
Labels: :sparkles: feat

#99 ♻️ Refactor: HTTP method 변경
  src/main/java/treehouse/server/api/treehouse/presentation/TreehouseApi.java
Labels: :hammer: code_edit

#101 🐛 Fix: @Transactional 제거
  src/main/java/treehouse/server/api/branch/business/BranchService.java
Labels: :hammer: code_edit

#102 Feat: FCM 도입 및 푸시 알림 테스트 구현
  .gitignore
  build.gradle
  src/main/java/treehouse/server/api/branch/business/BranchService.java
  src/main/java/treehouse/server/api/root/presentation/RootApi.java
  src/main/java/treehouse/server/api/treehouse/business/TreehouseMapper.java
  src/main/java/treehouse/server/api/treehouse/business/TreehouseService.java
  src/main/java/treehouse/server/api/treehouse/implementation/TreehouseQueryAdapter.java
  src/main/java/treehouse/server/api/treehouse/persistence/TreehouseRepository.java
  src/main/java/treehouse/server/api/treehouse/presentation/TreehouseApi.java
  src/main/java/treehouse/server/api/treehouse/presentation/dto/TreehouseRequestDTO.java
  src/main/java/treehouse/server/api/treehouse/presentation/dto/TreehouseResponseDTO.java
  src/main/java/treehouse/server/api/user/persistence/FcmTokenRepository.java
  src/main/java/treehouse/server/global/entity/User/FcmToken.java
  src/main/java/treehouse/server/global/entity/User/User.java
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
  src/main/java/treehouse/server/global/exception/ThrowClass/FcmException.java
  src/main/java/treehouse/server/global/fcm/FcmInit.java
  src/main/java/treehouse/server/global/fcm/dto/FCMDto.java
  src/main/java/treehouse/server/global/fcm/service/FcmService.java
  src/main/java/treehouse/server/global/feign/client/FCMFeignClient.java
  src/main/java/treehouse/server/global/feign/config/FCMFeignConfig.java
  src/main/java/treehouse/server/global/feign/dto/FCMResponseDto.java
  src/main/resources/application.yml
Labels: :bug: bug, :sparkles: feat

#106 ✨ Feat: 회원탈퇴 API 구현
  src/main/java/treehouse/server/api/member/business/MemberMapper.java
  src/main/java/treehouse/server/api/user/business/UserMapper.java
  src/main/java/treehouse/server/api/user/business/UserService.java
  src/main/java/treehouse/server/api/user/implement/UserCommandAdapter.java
  src/main/java/treehouse/server/api/user/presentation/UserApi.java
  src/main/java/treehouse/server/api/user/presentation/dto/UserResponseDTO.java
  src/main/java/treehouse/server/global/entity/User/User.java
  src/main/java/treehouse/server/global/entity/member/Member.java
Labels: :sparkles: feat

#107 Feat/104 FCM 푸시 알림 관련 로직 추가, API 추가
  src/main/java/treehouse/server/api/notification/business/NotificationService.java
  src/main/java/treehouse/server/api/user/business/UserMapper.java
  src/main/java/treehouse/server/api/user/business/UserService.java
  src/main/java/treehouse/server/api/user/presentation/UserApi.java
  src/main/java/treehouse/server/api/user/presentation/dto/UserRequestDTO.java
  src/main/java/treehouse/server/api/user/presentation/dto/UserResponseDTO.java
  src/main/java/treehouse/server/global/entity/User/FcmToken.java
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
  src/main/java/treehouse/server/global/fcm/service/FcmService.java
Labels: :sparkles: feat

#108 🐛 Fix: 푸시 알림 동의/거부 여부에 따른 알림 처리 추가
  src/main/java/treehouse/server/api/notification/business/NotificationService.java
Labels: :bug: bug

#110 🐛 Fix: Notification receiver 이슈 해결
  src/main/java/treehouse/server/api/member/business/MemberMapper.java
  src/main/java/treehouse/server/api/member/implementation/MemberQueryAdapter.java
  src/main/java/treehouse/server/api/notification/business/NotificationMapper.java
  src/main/java/treehouse/server/api/notification/business/NotificationService.java
  src/main/java/treehouse/server/api/user/business/UserMapper.java
  src/main/java/treehouse/server/global/entity/User/User.java
  src/main/java/treehouse/server/global/entity/member/Member.java
  src/main/java/treehouse/server/global/entity/notification/Notification.java
Labels: :bug: bug

#112 🐛 Fix: 아직 회원가입 하지 않은 사람에게 초대장을 보낸 경우, 알림 데이터 생성하지 않도록 수정
  src/main/java/treehouse/server/api/invitation/business/InvitationService.java
  src/main/java/treehouse/server/api/notification/business/NotificationService.java
  src/main/java/treehouse/server/api/user/implement/UserQueryAdapter.java
Labels: :bug: bug, :hammer: code_edit

#113 🐛 푸시 알림 동의 여부 확인 대상 변경
  src/main/java/treehouse/server/api/notification/business/NotificationService.java
  src/main/java/treehouse/server/global/fcm/service/FcmService.java
Labels: :bug: bug

#115 ✨ Feat: 초대 관련 부가기능 구현
  src/main/java/treehouse/server/api/invitation/business/InvitationService.java
  src/main/java/treehouse/server/api/invitation/implement/InvitationQueryAdapter.java
  src/main/java/treehouse/server/api/invitation/persistence/InvitationRepository.java
  src/main/java/treehouse/server/api/notification/business/NotificationService.java
  src/main/java/treehouse/server/global/entity/User/User.java
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
Labels: :sparkles: feat
