Repository Team-Shaka/Treehouse-SpringBoot, pull requests merged in 2024-07, with the labels that each got.

#73 ✨ Feat: 내 프로필 조회, 내 프로필 수정, 트리하우스 생성 기능 구현
  src/main/java/treehouse/server/api/branch/business/BranchService.java
  src/main/java/treehouse/server/api/branch/business/BranchUtil.java
  src/main/java/treehouse/server/api/comment/business/CommentMapper.java
  src/main/java/treehouse/server/api/comment/presentation/dto/CommentResponseDTO.java
  src/main/java/treehouse/server/api/member/business/MemberMapper.java
  src/main/java/treehouse/server/api/member/business/MemberService.java
  src/main/java/treehouse/server/api/member/presentation/MemberApi.java
  src/main/java/treehouse/server/api/member/presentation/dto/MemberRequestDTO.java
  src/main/java/treehouse/server/api/member/presentation/dto/MemberResponseDTO.java
  src/main/java/treehouse/server/api/post/business/PostMapper.java
  src/main/java/treehouse/server/api/post/presentation/dto/PostResponseDTO.java
  src/main/java/treehouse/server/api/treehouse/business/TreehouseMapper.java
  src/main/java/treehouse/server/api/treehouse/business/TreehouseService.java
  src/main/java/treehouse/server/api/treehouse/implementation/TreehouseCommandAdapter.java
  src/main/java/treehouse/server/api/treehouse/presentation/TreehouseApi.java
  src/main/java/treehouse/server/api/treehouse/presentation/dto/TreehouseRequestDTO.java
  src/main/java/treehouse/server/api/treehouse/presentation/dto/TreehouseResponseDTO.java
  src/main/java/treehouse/server/global/entity/member/Member.java
Labels: :sparkles: feat

#76 Feat/71 Comment 관련 Request, Response 관련 수정 및 변경
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/comment/presentation/dto/CommentRequestDTO.java
Labels: :hammer: code_edit

#77 Feat/71 대댓글 관련 로직 및 조회, 작성 API 구현
  src/main/java/treehouse/server/api/comment/business/CommentMapper.java
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/comment/implementation/CommentQueryAdapter.java
  src/main/java/treehouse/server/api/comment/persistence/CommentRepository.java
  src/main/java/treehouse/server/api/comment/presentation/CommentApi.java
  src/main/java/treehouse/server/api/comment/presentation/dto/CommentResponseDTO.java
  src/main/java/treehouse/server/global/entity/comment/Comment.java
  src/main/java/treehouse/server/global/entity/comment/CommentType.java
Labels: :sparkles: feat

#78 Feat/71 댓글 작성, 삭제 관련 예외 처리 추가
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/comment/presentation/CommentApi.java
  src/main/java/treehouse/server/global/exception/GlobalErrorCode.java
Labels: :sparkles: feat

#80 Feat/79 트리하우스 멤버 프로필, 멤버가 작성한 게시글 조회 API 구현, 댓글 시각 형식 변경
  src/main/java/treehouse/server/api/comment/business/CommentMapper.java
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/member/business/MemberMapper.java
  src/main/java/treehouse/server/api/member/business/MemberService.java
  src/main/java/treehouse/server/api/member/presentation/MemberApi.java
  src/main/java/treehouse/server/api/member/presentation/dto/MemberResponseDTO.java
  src/main/java/treehouse/server/api/post/business/PostMapper.java
  src/main/java/treehouse/server/api/post/business/PostService.java
  src/main/java/treehouse/server/api/post/implement/PostQueryAdapter.java
  src/main/java/treehouse/server/api/post/persistence/PostRepository.java
  src/main/java/treehouse/server/api/post/presentation/dto/PostResponseDTO.java
Labels: :bug: bug, :sparkles: feat

#81 📝 Docs: API 명세 보완
  src/main/java/treehouse/server/api/comment/presentation/CommentApi.java
  src/main/java/treehouse/server/api/member/presentation/MemberApi.java
  src/main/java/treehouse/server/api/notification/presentation/NotificationApi.java
  src/main/java/treehouse/server/api/post/presentation/PostApi.java
Labels: :memo: docs

#82 📝 Docs: 스웨거 명세 수정
  src/main/java/treehouse/server/api/invitation/presentation/InvitationApi.java
  src/main/java/treehouse/server/api/member/presentation/MemberApi.java
  src/main/java/treehouse/server/api/notification/presentation/NotificationApi.java
Labels: :memo: docs

#83 Feature/75 - 트리하우스 정보 조회 API 및 하드코딩으로 채워뒀던 코드들 수정
  src/main/java/treehouse/server/api/comment/business/CommentMapper.java
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/invitation/business/InvitationMapper.java
  src/main/java/treehouse/server/api/invitation/business/InvitationService.java
  src/main/java/treehouse/server/api/invitation/implement/InvitationQueryAdapter.java
  src/main/java/treehouse/server/api/invitation/presentation/dto/InvitationResponseDTO.java
  src/main/java/treehouse/server/api/member/business/MemberMapper.java
  src/main/java/treehouse/server/api/post/business/PostMapper.java
  src/main/java/treehouse/server/api/post/business/PostService.java
  src/main/java/treehouse/server/api/treehouse/business/TreehouseMapper.java
  src/main/java/treehouse/server/api/treehouse/business/TreehouseService.java
  src/main/java/treehouse/server/api/treehouse/presentation/TreehouseApi.java
  src/main/java/treehouse/server/api/treehouse/presentation/dto/TreehouseResponseDTO.java
  src/main/java/treehouse/server/global/entity/Invitation/Invitation.java
  src/main/java/treehouse/server/global/exception/ThrowClass/InvitationException.java
Labels: :sparkles: feat, :hammer: code_edit

#85 ✨ Feat: 알림 조회 문구의 구체화 및 읽음 처리 기능
  src/main/java/treehouse/server/api/comment/business/CommentService.java
  src/main/java/treehouse/server/api/invitation/business/InvitationService.java
  src/main/java/treehouse/server/api/notification/business/NotificationMapper.java
  src/main/java/treehouse/server/api/notification/business/NotificationService.java
  src/main/java/treehouse/server/api/notification/business/NotificationUtil.java
  src/main/java/treehouse/server/api/notification/implement/NotificationCommandAdapter.java
  src/main/java/treehouse/server/api/notification/implement/NotificationQueryAdapter.java
  src/main/java/treehouse/server/api/notification/presentation/NotificationApi.java
  src/main/java/treehouse/server/api/notification/presentation/dto/NotificationRequestDTO.java
  src/main/java/treehouse/server/api/notification/presentation/dto/NotificationResponseDTO.java
  src/main/java/treehouse/server/api/post/business/PostService.java
  src/main/java/treehouse/server/global/entity/notification/Notification.java
  src/main/java/treehouse/server/global/exception/ThrowClass/NotificationException.java
Labels: :sparkles: feat

#87 ✨ Feat: 내가 가입한 트리하우스 목록 조회
  src/main/java/treehouse/server/api/treehouse/business/TreehouseMapper.java
  src/main/java/treehouse/server/api/treehouse/business/TreehouseService.java
  src/main/java/treehouse/server/api/treehouse/presentation/TreehouseApi.java
  src/main/java/treehouse/server/api/treehouse/presentation/dto/TreehouseResponseDTO.java
  src/main/java/treehouse/server/api/user/business/UserMapper.java
  src/main/java/treehouse/server/api/user/presentation/dto/UserResponseDTO.java
  src/main/java/treehouse/server/global/entity/treeHouse/TreeHouse.java
Labels: :sparkles: feat
